// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwLYhmxAQcVQMEOpLNviyYrHMqLYtCp5c',
    appId: '1:385184480101:web:0f34ffbc6e985001d9ff8c',
    messagingSenderId: '385184480101',
    projectId: 'todo-public-9c716',
    authDomain: 'todo-public-9c716.firebaseapp.com',
    storageBucket: 'todo-public-9c716.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBunD96uft51TQQdnisplJgUd9XcZh_zsg',
    appId: '1:385184480101:android:fe1fc7aa013d4e3fd9ff8c',
    messagingSenderId: '385184480101',
    projectId: 'todo-public-9c716',
    storageBucket: 'todo-public-9c716.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd50RoTE3Z7UslrQZ_ANWhrJS-UiYvR-4',
    appId: '1:385184480101:ios:9361a5fd33e68b3dd9ff8c',
    messagingSenderId: '385184480101',
    projectId: 'todo-public-9c716',
    storageBucket: 'todo-public-9c716.appspot.com',
    iosBundleId: 'com.example.apnanotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd50RoTE3Z7UslrQZ_ANWhrJS-UiYvR-4',
    appId: '1:385184480101:ios:47eac5281669080bd9ff8c',
    messagingSenderId: '385184480101',
    projectId: 'todo-public-9c716',
    storageBucket: 'todo-public-9c716.appspot.com',
    iosBundleId: 'com.example.apnanotes.RunnerTests',
  );
}
